### ISSUE TITLE
Not client-side, vanilla lobbies break the game (bug)

### ISSUE THREAD

**Issue by Hlebuw3k** [Goorakh/CollapseDisplay#1]
Joining a vanilla lobby with this mod installed breaks the game, all enemies and players appear frozen in place (and I can't even exit the drop pod) demonstrated by joining a random in-progress lobby here, with ONLY this mod and dependancies installed: https://youtu.be/GtCF9TRJcsI
I tried joining several other lobbies and the result is the same, the game is unplayable if the host does not have this mod too.

**Comment by Goorakh** [comment]
Since version 1.2.0 the mod is no longer clientside.

Though I did apparently forget to remove the clientside tag on Thunderstore, which is now fixed.
